# Generated by Django 3.0.8 on 2020-12-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField()),
                ('interval', models.CharField(max_length=50)),
                ('notifications', models.IntegerField()),
                ('apps', models.IntegerField()),
                ('description', models.TextField(null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('status', models.BooleanField(default=True)),
                ('payment_method', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('subscription_created_at', models.CharField(blank=True, max_length=255, null=True)),
                ('charge_receipt_url', models.CharField(blank=True, max_length=555, null=True)),
            ],
        ),
    ]
