# Generated by Django 3.0.8 on 2020-12-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoices',
            name='charge_receipt_url',
            field=models.CharField(blank=True, max_length=555, null=True),
        ),
    ]
