# Generated by Django 3.0.8 on 2020-11-25 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
                ('notifications_used', models.IntegerField(default=0)),
                ('app_qr', models.ImageField(blank=True, upload_to='app_qr/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('app_image', models.ImageField(blank=True, upload_to='app_image/')),
                ('app_logo', models.ImageField(blank=True, upload_to='app_logo/')),
                ('app_url', models.CharField(max_length=500)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserApp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('app_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app', to='app.App')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='users.User')),
            ],
        ),
    ]
