# Generated by Django 3.0.8 on 2021-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='notifications_actual_used',
            field=models.IntegerField(default=0),
        ),
    ]
