<<<<<<< HEAD
# Generated by Django 3.0.8 on 2021-02-01 19:16
=======
# Generated by Django 3.0.8 on 2021-02-01 17:17
>>>>>>> a727afb5780df87932ca59662cc1f73c27dd4658

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_app_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='notifications_actual_used',
            field=models.IntegerField(default=0),
        ),
    ]
