# Generated by Django 3.0.8 on 2021-03-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appprivate_privateqr_privateuserapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateqr',
            name='qr_code',
            field=models.CharField(default='sdsdsd', max_length=500),
            preserve_default=False,
        ),
    ]
