# Generated by Django 3.0.8 on 2021-03-21 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_privateqr_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateqr',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
