# Generated by Django 3.0.8 on 2020-12-03 18:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_remove_userapp_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='customer_id',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='cust_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
