# Generated by Django 3.0.8 on 2020-12-03 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_userapp_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='customer_id',
        ),
    ]
