# Generated by Django 3.0.8 on 2020-12-04 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_userapp_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='customer_id',
            field=models.IntegerField(null=True),
        ),
    ]
