# Generated by Django 3.0.8 on 2020-12-03 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='email_notifications',
            new_name='total_notifications_sent',
        ),
    ]
