# Generated by Django 3.0.8 on 2020-11-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='customer_image/'),
        ),
        migrations.AddField(
            model_name='customer',
            name='used_notifications',
            field=models.IntegerField(default=0),
        ),
    ]
