# Generated by Django 3.0.8 on 2020-10-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_userapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapp',
            name='description',
            field=models.CharField(default='mohsan', max_length=100),
        ),
    ]
