# Generated by Django 3.0.8 on 2020-10-01 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_userapp_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapp',
            name='description',
        ),
    ]
