# Generated by Django 3.0.8 on 2020-11-19 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_remove_userapp_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_logo',
            field=models.ImageField(blank=True, upload_to='app_logo/'),
        ),
        migrations.AlterField(
            model_name='app',
            name='app_image',
            field=models.ImageField(blank=True, upload_to='app_image/'),
        ),
    ]
