# Generated by Django 3.0.8 on 2020-11-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_auto_20201119_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='app',
            name='app_url',
            field=models.CharField(default='myapp.com', max_length=500),
            preserve_default=False,
        ),
    ]
