# Generated by Django 3.0.8 on 2020-12-09 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_count',
            field=models.IntegerField(default=0),
        ),
    ]
