# Generated by Django 3.0.8 on 2021-02-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20210118_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='description',
            field=models.CharField(default='my description', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usernotification',
            name='title',
            field=models.CharField(default='my titile', max_length=200),
            preserve_default=False,
        ),
    ]
